"""Phase 1 — 파이썬 기초 (레벨 1~16).

실제 수강한 강의(course_dev_basic/Program Language/Python)의 노트북 순서와
깊이를 참고해서 구성했다. 원래 기획서의 레벨 1~10보다 범위가 넓다 —
튜플/집합, 컴프리헨션, 함수 심화(기본값/가변 인자/람다), 예외처리, 클래스
기초가 실제 강의에는 있었지만 기존 콘텐츠에는 빠져 있었다.
"""

LEVELS = [
    {
        "id": 1,
        "title": "Hello, Python",
        "goal": "print()와 코드 실행에 익숙해지기",
        "concepts": [
            {
                "id": "print-basics",
                "title": "print()로 화면에 출력하기",
                "explanation": "print는 컴퓨터에게 화면에 무언가를 보여 달라고 말하는 명령입니다. 괄호 안에 보여주고 싶은 내용을 넣습니다.",
                "example_code": 'print("안녕하세요")',
            },
            {
                "id": "string-quotes",
                "title": "문자열은 따옴표로 감싸기",
                "explanation": "글자(문자열)를 출력하려면 큰따옴표(\") 또는 작은따옴표(') 중 하나로 감싸야 합니다. 어떤 걸 써도 결과는 같습니다.",
                "example_code": "print('Python')",
            },
            {
                "id": "print-multiple",
                "title": "한 번에 여러 값 출력하기",
                "explanation": "print에 콤마(,)로 값을 여러 개 넘기면 자동으로 띄어쓰기가 들어간 채로 한 줄에 출력됩니다. print를 여러 번 부르면 줄이 바뀌고, 문자열 안에 \\n을 넣어도 줄이 바뀝니다.",
                "example_code": 'print("Hello", "World")',
            },
        ],
        "problems": [
            {
                "id": "p1-print-hello",
                "concept_id": "print-basics",
                "prompt": '화면에 정확히 "안녕하세요" 를 출력하세요.',
                "reference_code": 'print("안녕하세요")',
                "hints": [
                    "화면에 내용을 출력할 때 쓰는 함수를 떠올려 보세요.",
                    "글자는 큰따옴표나 작은따옴표로 감싸야 합니다.",
                    'print("안녕하세요")',
                ],
            },
            {
                "id": "p2-single-quotes",
                "concept_id": "string-quotes",
                "prompt": '작은따옴표를 사용해서 정확히 "안녕, 파이썬!" 을 출력하세요.',
                "reference_code": "print('안녕, 파이썬!')",
                "hints": [
                    "큰따옴표 대신 작은따옴표로도 문자열을 감쌀 수 있습니다.",
                    "print( ) 괄호 안에 작은따옴표로 감싼 글자를 넣어보세요.",
                    "print('안녕, 파이썬!')",
                ],
            },
            {
                "id": "p3-multiple-values",
                "concept_id": "print-multiple",
                "prompt": 'print에 "Hello"와 "World" 두 값을 콤마로 넘겨서 정확히 "Hello World" 를 출력하세요.',
                "reference_code": 'print("Hello", "World")',
                "hints": [
                    "print 괄호 안에 값을 콤마(,)로 구분해서 여러 개 넣을 수 있습니다.",
                    "콤마로 넘긴 값 사이에는 자동으로 띄어쓰기가 한 칸 들어갑니다.",
                    'print("Hello", "World")',
                ],
            },
            {
                "id": "p4-escape-quote",
                "concept_id": "string-quotes",
                "prompt": '정확히 다음과 같이 출력하세요 (따옴표 포함): 그는 "안녕"이라고 말했다',
                "reference_code": "print('그는 \"안녕\"이라고 말했다')",
                "hints": [
                    "문자열 안에 큰따옴표를 그대로 넣고 싶다면, 문자열 전체는 다른 종류의 따옴표로 감싸면 편합니다.",
                    "전체 문자열을 작은따옴표(')로 감싸고, 안에는 큰따옴표(\")를 그대로 쓰세요.",
                    "print('그는 \"안녕\"이라고 말했다')",
                ],
            },
            {
                "id": "p5-mini-self-intro",
                "concept_id": "print-multiple",
                "prompt": "미니 프로젝트: 아래 세 줄을 정확히 그대로 출력하는 자기소개 출력기를 만드세요.\n이름: 파이코치\n취미: 코딩\n목표: 파이썬 마스터",
                "reference_code": 'print("이름: 파이코치")\nprint("취미: 코딩")\nprint("목표: 파이썬 마스터")',
                "hints": [
                    "지금까지 배운 것처럼 print를 여러 번 사용하거나 \\n을 활용할 수 있습니다.",
                    "한 줄씩 print를 세 번 쓰는 게 가장 실수하기 어렵습니다.",
                    'print("이름: 파이코치")\nprint("취미: 코딩")\nprint("목표: 파이썬 마스터")',
                ],
            },
        ],
    },
    {
        "id": 2,
        "title": "변수와 입력",
        "goal": "값을 저장하고 사용자 입력 받기",
        "concepts": [
            {
                "id": "variables",
                "title": "변수에 값 저장하기",
                "explanation": "변수는 값을 담아두는 상자입니다. '이름 = 값' 형태로 값을 저장하고, 이름만 써서 다시 꺼내 쓸 수 있습니다.",
                "example_code": 'name = "파이코치"\nprint(name)',
            },
            {
                "id": "input-basics",
                "title": "input()으로 사용자 입력받기",
                "explanation": "input()은 사용자가 키보드로 입력한 내용을 문자열로 돌려줍니다. 보통 변수에 저장해서 사용합니다.",
                "example_code": "name = input()\nprint(name)",
                "stdin_for_example": "홍길동\n",
            },
            {
                "id": "string-concat",
                "title": "문자열끼리 합치기 (+)",
                "explanation": "문자열은 + 연산자로 이어 붙일 수 있습니다. 변수와 고정된 문자열을 합쳐서 문장을 만들 때 자주 씁니다.",
                "example_code": 'name = "파이코치"\nprint("안녕하세요, " + name + "님!")',
            },
        ],
        "problems": [
            {
                "id": "p1-store-variable",
                "concept_id": "variables",
                "prompt": 'name이라는 변수에 "파이코치"를 저장하고, name을 출력하세요.',
                "reference_code": 'name = "파이코치"\nprint(name)',
                "hints": [
                    "변수는 '이름 = 값' 형태로 만듭니다.",
                    'name = "파이코치" 로 저장한 뒤, print(name)으로 변수를 출력하세요.',
                    'name = "파이코치"\nprint(name)',
                ],
            },
            {
                "id": "p2-echo-input",
                "concept_id": "input-basics",
                "prompt": "input()으로 이름을 입력받아, 입력받은 값을 그대로 출력하세요.",
                "reference_code": "name = input()\nprint(name)",
                "stdin": "파이코치\n",
                "input_hint": "아무 이름이나 입력해보세요. 예: 홍길동",
                "hints": [
                    "input()의 결과를 변수에 저장한 다음 그 변수를 출력해보세요.",
                    "name = input() 처럼 저장하고, print(name)으로 출력합니다.",
                    "name = input()\nprint(name)",
                ],
            },
            {
                "id": "p3-greeting",
                "concept_id": "string-concat",
                "prompt": 'input()으로 이름을 입력받아, "안녕하세요, OOO님!" 형태로 인사말을 출력하세요. (OOO 자리에 입력한 이름)',
                "reference_code": 'name = input()\nprint("안녕하세요, " + name + "님!")',
                "stdin": "파이코치\n",
                "input_hint": "이름을 입력해보세요. 예: 홍길동",
                "hints": [
                    "먼저 입력값을 변수에 저장하세요.",
                    "문자열 + 변수 + 문자열 형태로 이어 붙이면 문장을 만들 수 있습니다.",
                    'name = input()\nprint("안녕하세요, " + name + "님!")',
                ],
            },
            {
                "id": "p4-two-variables",
                "concept_id": "variables",
                "prompt": 'city 변수에 "서울", hobby 변수에 "코딩"을 저장하고, 아래처럼 두 줄로 출력하세요.\n사는 곳: 서울\n취미: 코딩',
                "reference_code": 'city = "서울"\nhobby = "코딩"\nprint("사는 곳: " + city)\nprint("취미: " + hobby)',
                "hints": [
                    "변수를 두 개 만들어야 합니다. city와 hobby 각각에 값을 저장하세요.",
                    'print("사는 곳: " + city) 처럼 고정 문구와 변수를 합쳐서 출력하세요.',
                    'city = "서울"\nhobby = "코딩"\nprint("사는 곳: " + city)\nprint("취미: " + hobby)',
                ],
            },
            {
                "id": "p5-mini-age-greeting",
                "concept_id": "string-concat",
                "prompt": 'input()으로 이름과 나이를 순서대로 입력받아 "OOO님은 OO살입니다." 형식으로 출력하세요.',
                "reference_code": 'name = input()\nage = input()\nprint(name + "님은 " + age + "살입니다.")',
                "stdin": "파이코치\n5\n",
                "input_hint": "첫 줄에 이름, 둘째 줄에 나이를 입력해보세요. 예: 홍길동 / 10",
                "hints": [
                    "input()을 두 번 호출해서 이름과 나이를 각각 저장하세요.",
                    "age도 input()의 결과라 이미 문자열이라서 그대로 + 로 이어 붙일 수 있습니다.",
                    'name = input()\nage = input()\nprint(name + "님은 " + age + "살입니다.")',
                ],
            },
        ],
    },
    {
        "id": 3,
        "title": "문자열 다루기",
        "goal": "인덱싱·슬라이싱, 이스케이프, 포매팅과 문자열 함수",
        "concepts": [
            {
                "id": "string-index-slice",
                "title": "문자열 인덱싱과 슬라이싱",
                "explanation": "문자열도 리스트처럼 문자열[인덱스]로 한 글자를, 문자열[시작:끝]으로 여러 글자를 잘라낼 수 있습니다. 인덱스는 0부터 시작하고, -1은 맨 뒤 글자를 뜻합니다.",
                "example_code": 'a = "Hello World"\nprint(a[0])\nprint(a[6:])',
            },
            {
                "id": "escape-chars",
                "title": "이스케이프 문자",
                "explanation": "\\n(줄바꿈), \\t(탭), \\\\(역슬래시 자체), \\'와 \\\"(따옴표를 그대로 표현)처럼 문자열 안에서 특별한 의미를 갖는 문자 조합입니다.",
                "example_code": 'print("이름\\t나이")',
            },
            {
                "id": "fstring-and-functions",
                "title": "f-string과 문자열 함수",
                "explanation": 'f"...{변수}..." 형태로 문자열 안에 변수를 바로 넣을 수 있습니다. len()/upper()/lower()/strip()/replace() 같은 함수로 문자열을 다룰 수도 있습니다.',
                "example_code": 'name = "파이썬"\nprint(f"안녕, {name}!")',
            },
        ],
        "problems": [
            {
                "id": "p1-first-last-char",
                "concept_id": "string-index-slice",
                "prompt": '"Hello World"에서 첫 글자와 마지막 글자를 각각 한 줄씩 출력하세요.',
                "reference_code": 'a = "Hello World"\nprint(a[0])\nprint(a[-1])',
                "hints": [
                    "인덱스는 0부터 시작합니다. a[0]이 첫 글자입니다.",
                    "a[-1]은 맨 뒤에서 첫 번째, 즉 마지막 글자입니다.",
                    'a = "Hello World"\nprint(a[0])\nprint(a[-1])',
                ],
            },
            {
                "id": "p2-slice-hello",
                "concept_id": "string-index-slice",
                "prompt": '"Hello World"에서 앞 5글자("Hello")만 슬라이싱으로 잘라 출력하세요.',
                "reference_code": 'a = "Hello World"\nprint(a[:5])',
                "hints": [
                    "슬라이싱 a[시작:끝]에서 시작을 생략하면 처음부터라는 뜻입니다.",
                    "a[:5]는 인덱스 0부터 4까지, 즉 앞 5글자를 잘라냅니다.",
                    'a = "Hello World"\nprint(a[:5])',
                ],
            },
            {
                "id": "p3-tab-escape",
                "concept_id": "escape-chars",
                "prompt": '\\t를 사용해서 "이름"과 "나이" 사이를 탭으로 띄운 "이름\\t나이" 를 출력하세요.',
                "reference_code": 'print("이름\\t나이")',
                "hints": [
                    "탭 간격을 줄 때 쓰는 이스케이프 문자를 떠올려 보세요.",
                    "\\t를 문자열 중간에 그대로 넣으면 됩니다.",
                    'print("이름\\t나이")',
                ],
            },
            {
                "id": "p4-fstring",
                "concept_id": "fstring-and-functions",
                "prompt": 'name = "파이코치", age = 5 변수를 만들고, f-string으로 "이름: 파이코치, 나이: 5" 형식으로 출력하세요.',
                "reference_code": 'name = "파이코치"\nage = 5\nprint(f"이름: {name}, 나이: {age}")',
                "hints": [
                    "문자열 앞에 f를 붙이면 중괄호 { } 안에 변수를 바로 넣을 수 있습니다.",
                    'f"이름: {name}, 나이: {age}" 형태로 써보세요.',
                    'name = "파이코치"\nage = 5\nprint(f"이름: {name}, 나이: {age}")',
                ],
            },
            {
                "id": "p5-mini-string-functions",
                "concept_id": "fstring-and-functions",
                "prompt": '"  Hello World  " 문자열의 양쪽 공백을 제거(strip)하고, 소문자로 바꾼(lower) 뒤, 공백을 "-"로 치환(replace)해서 출력하세요.',
                "reference_code": 'a = "  Hello World  "\na = a.strip()\na = a.lower()\na = a.replace(" ", "-")\nprint(a)',
                "hints": [
                    "strip()으로 양쪽 공백을 지우고, lower()로 소문자로 바꾸는 걸 순서대로 적용하세요.",
                    "마지막으로 replace(\" \", \"-\")로 남은 공백을 하이픈으로 바꾸세요.",
                    'a = "  Hello World  "\na = a.strip()\na = a.lower()\na = a.replace(" ", "-")\nprint(a)',
                ],
            },
        ],
    },
    {
        "id": 4,
        "title": "숫자와 연산",
        "goal": "형변환, 사칙연산, 제곱·나머지·몫, 비교 연산자",
        "concepts": [
            {
                "id": "numbers",
                "title": "정수와 실수, 사칙연산",
                "explanation": "파이썬 숫자는 정수(int)와 실수(float)가 있습니다. +, -, *, / 로 계산할 수 있고, /는 항상 실수(float) 결과를 돌려줍니다.",
                "example_code": "print(3 + 5)",
            },
            {
                "id": "type-conversion",
                "title": "input()은 항상 문자열",
                "explanation": "input()으로 받은 값은 계산 없이 그냥 쓰면 숫자가 아니라 문자열입니다. 계산하려면 int()나 float()로 바꿔야 합니다.",
                "example_code": "n = int(input())\nprint(n + 1)",
                "stdin_for_example": "10\n",
            },
            {
                "id": "power-floordiv-mod",
                "title": "제곱, 몫, 나머지",
                "explanation": "a**b는 a의 b제곱, a//b는 나눗셈의 몫(소수점 버림), a%b는 나눗셈의 나머지입니다.",
                "example_code": "print(2 ** 10)\nprint(17 // 5)\nprint(17 % 5)",
            },
            {
                "id": "booleans",
                "title": "불리언과 비교 연산자",
                "explanation": "==, >, < 같은 비교 연산자의 결과는 True 또는 False(불리언)입니다.",
                "example_code": "print(7 > 10)",
            },
        ],
        "problems": [
            {
                "id": "p1-add",
                "concept_id": "numbers",
                "prompt": "3과 5를 더한 결과를 출력하세요.",
                "reference_code": "print(3 + 5)",
                "hints": [
                    "print 안에 계산식을 그대로 넣을 수 있습니다.",
                    "print(3 + 5) 처럼 써보세요.",
                    "print(3 + 5)",
                ],
            },
            {
                "id": "p2-input-add",
                "concept_id": "type-conversion",
                "prompt": "input()으로 숫자 두 개를 한 줄씩 입력받아 더한 값을 출력하세요.",
                "reference_code": "a = int(input())\nb = int(input())\nprint(a + b)",
                "stdin": "3\n5\n",
                "input_hint": "숫자를 한 줄씩 입력해보세요. 예: 3 / 5",
                "hints": [
                    "input()의 결과는 문자열이라 바로 더하면 오류가 납니다.",
                    "int()로 감싸서 숫자로 바꾼 다음 변수에 저장하세요.",
                    "a = int(input())\nb = int(input())\nprint(a + b)",
                ],
            },
            {
                "id": "p3-power",
                "concept_id": "power-floordiv-mod",
                "prompt": "2의 10제곱을 출력하세요.",
                "reference_code": "print(2 ** 10)",
                "hints": [
                    "거듭제곱은 * 두 개를 이어 쓴 ** 연산자로 표현합니다.",
                    "print(2 ** 10)을 써보세요.",
                    "print(2 ** 10)",
                ],
            },
            {
                "id": "p4-floordiv-mod",
                "concept_id": "power-floordiv-mod",
                "prompt": "17을 5로 나눈 몫과 나머지를 각각 한 줄씩(몫이 먼저) 출력하세요.",
                "reference_code": "print(17 // 5)\nprint(17 % 5)",
                "hints": [
                    "몫은 //, 나머지는 % 연산자로 구합니다.",
                    "print(17 // 5)와 print(17 % 5)를 순서대로 쓰세요.",
                    "print(17 // 5)\nprint(17 % 5)",
                ],
            },
            {
                "id": "p5-comparison",
                "concept_id": "booleans",
                "prompt": "7이 10보다 큰지 비교한 결과를 출력하세요.",
                "reference_code": "print(7 > 10)",
                "hints": [
                    "비교 연산자를 사용하면 결과가 True/False로 나옵니다.",
                    "> 연산자로 두 숫자를 비교해보세요.",
                    "print(7 > 10)",
                ],
            },
            {
                "id": "p6-mini-calculator",
                "concept_id": "type-conversion",
                "prompt": "input()으로 숫자 두 개를 입력받아 합, 차, 곱을 아래 형식으로 출력하는 간단한 계산기를 만드세요.\n합: N\n차: N\n곱: N",
                "reference_code": 'a = int(input())\nb = int(input())\nprint("합:", a + b)\nprint("차:", a - b)\nprint("곱:", a * b)',
                "stdin": "4\n2\n",
                "input_hint": "숫자를 한 줄씩 입력해보세요. 예: 4 / 2",
                "hints": [
                    "먼저 두 입력값을 int()로 변환해서 변수에 저장하세요.",
                    'print("합:", a + b) 처럼 콤마로 이어서 출력하면 자동으로 띄어쓰기가 들어갑니다.',
                    'a = int(input())\nb = int(input())\nprint("합:", a + b)\nprint("차:", a - b)\nprint("곱:", a * b)',
                ],
            },
        ],
    },
    {
        "id": 5,
        "title": "조건문 if",
        "goal": "상황에 따라 다른 동작 만들기",
        "concepts": [
            {
                "id": "if-basics",
                "title": "if문 기본 구조",
                "explanation": "if 조건: 다음 줄에 들여쓰기한 코드는 조건이 참(True)일 때만 실행됩니다.",
                "example_code": 'if 10 > 5:\n    print("10은 5보다 큽니다")',
            },
            {
                "id": "if-else",
                "title": "if / else",
                "explanation": "else는 if 조건이 거짓일 때 실행할 코드를 정합니다. 둘 중 하나는 반드시 실행됩니다.",
                "example_code": 'n = 3\nif n % 2 == 0:\n    print("짝수")\nelse:\n    print("홀수")',
            },
            {
                "id": "elif",
                "title": "elif로 여러 조건 비교하기",
                "explanation": "elif를 쓰면 조건을 여러 개 순서대로 검사할 수 있습니다. 위에서부터 참인 조건 하나만 실행됩니다.",
                "example_code": 'score = 85\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelse:\n    print("C")',
            },
        ],
        "problems": [
            {
                "id": "p1-if-basic",
                "concept_id": "if-basics",
                "prompt": '숫자 10이 5보다 크면 "10은 5보다 큽니다"를 출력하는 코드를 작성하세요.',
                "reference_code": 'if 10 > 5:\n    print("10은 5보다 큽니다")',
                "hints": [
                    "if 조건: 다음 줄을 들여쓰기해서 실행할 코드를 씁니다.",
                    "if 10 > 5: 다음 줄에 print를 들여써서 넣어보세요.",
                    'if 10 > 5:\n    print("10은 5보다 큽니다")',
                ],
            },
            {
                "id": "p2-odd-even",
                "concept_id": "if-else",
                "prompt": 'input()으로 숫자를 하나 입력받아, 짝수면 "짝수입니다", 홀수면 "홀수입니다"를 출력하세요.',
                "reference_code": 'n = int(input())\nif n % 2 == 0:\n    print("짝수입니다")\nelse:\n    print("홀수입니다")',
                "stdin": "4\n",
                "input_hint": "숫자를 입력해보세요. 예: 4",
                "hints": [
                    "짝수인지는 % 2 == 0으로 확인할 수 있습니다 (나머지가 0이면 짝수).",
                    "if로 짝수 조건을 검사하고, else로 나머지 경우를 처리하세요.",
                    'n = int(input())\nif n % 2 == 0:\n    print("짝수입니다")\nelse:\n    print("홀수입니다")',
                ],
            },
            {
                "id": "p3-adult-check",
                "concept_id": "if-else",
                "prompt": 'input()으로 나이를 입력받아, 19살 이상이면 "성인입니다", 아니면 "미성년자입니다"를 출력하세요.',
                "reference_code": 'age = int(input())\nif age >= 19:\n    print("성인입니다")\nelse:\n    print("미성년자입니다")',
                "stdin": "20\n",
                "input_hint": "나이를 입력해보세요. 예: 20",
                "hints": [
                    "'19살 이상'은 >= 연산자로 표현합니다.",
                    'if age >= 19: 조건이 참이면 성인, else면 미성년자를 출력하세요.',
                    'age = int(input())\nif age >= 19:\n    print("성인입니다")\nelse:\n    print("미성년자입니다")',
                ],
            },
            {
                "id": "p4-grade",
                "concept_id": "elif",
                "prompt": 'input()으로 점수를 입력받아 90 이상이면 "A", 80 이상이면 "B", 그 외에는 "C"를 출력하세요.',
                "reference_code": 'score = int(input())\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelse:\n    print("C")',
                "stdin": "85\n",
                "input_hint": "점수를 입력해보세요. 예: 85",
                "hints": [
                    "조건이 세 가지(90 이상 / 80 이상 / 그 외)이므로 elif가 필요합니다.",
                    "if score >= 90, elif score >= 80, else 순서로 검사하세요. 순서가 중요합니다.",
                    'score = int(input())\nif score >= 90:\n    print("A")\nelif score >= 80:\n    print("B")\nelse:\n    print("C")',
                ],
            },
            {
                "id": "p5-mini-adult-checker",
                "concept_id": "elif",
                "prompt": 'input()으로 이름과 나이를 순서대로 입력받아, "OOO님은 성인입니다." 또는 "OOO님은 미성년자입니다."를 출력하세요. (19살 기준)',
                "reference_code": 'name = input()\nage = int(input())\nif age >= 19:\n    print(name + "님은 성인입니다.")\nelse:\n    print(name + "님은 미성년자입니다.")',
                "stdin": "파이코치\n17\n",
                "input_hint": "첫 줄에 이름, 둘째 줄에 나이를 입력해보세요. 예: 홍길동 / 17",
                "hints": [
                    "이름과 나이, 두 번 input()을 받아야 합니다. 나이는 숫자로 변환하세요.",
                    "문자열 이어붙이기(+)와 if/else를 함께 사용해보세요.",
                    'name = input()\nage = int(input())\nif age >= 19:\n    print(name + "님은 성인입니다.")\nelse:\n    print(name + "님은 미성년자입니다.")',
                ],
            },
        ],
    },
    {
        "id": 6,
        "title": "논리 연산과 멤버십",
        "goal": "and/or/not, in/not in, 삼항 표현식으로 조건 다루기",
        "concepts": [
            {
                "id": "logical-operators",
                "title": "and, or, not",
                "explanation": "and는 둘 다 참일 때, or는 둘 중 하나만 참이어도 True입니다. not은 참/거짓을 뒤집습니다.",
                "example_code": "x = 5\nprint(x > 0 and x < 10)",
            },
            {
                "id": "membership",
                "title": "in / not in 멤버 연산자",
                "explanation": "값 in 리스트(또는 문자열)는 그 값이 포함되어 있는지 확인합니다. not in은 반대로 포함되어 있지 않은지 확인합니다.",
                "example_code": 'fruits = ["사과", "바나나"]\nprint("사과" in fruits)',
            },
            {
                "id": "ternary",
                "title": "삼항 표현식 (조건부 표현식)",
                "explanation": "값1 if 조건 else 값2 형태로, if/else를 한 줄로 줄여 쓸 수 있습니다.",
                "example_code": 'a = 5\nprint("짝수" if a % 2 == 0 else "홀수")',
            },
        ],
        "problems": [
            {
                "id": "p1-and",
                "concept_id": "logical-operators",
                "prompt": "x = 7일 때, x가 0보다 크면서 동시에 10보다 작은지 and를 사용해서 출력하세요.",
                "reference_code": "x = 7\nprint(x > 0 and x < 10)",
                "hints": [
                    "두 조건을 모두 만족해야 True가 되는 연산자를 떠올려 보세요.",
                    "x > 0 and x < 10 을 그대로 출력하면 됩니다.",
                    "x = 7\nprint(x > 0 and x < 10)",
                ],
            },
            {
                "id": "p2-or",
                "concept_id": "logical-operators",
                "prompt": "숫자 15가 10보다 작거나 20보다 큰지 or를 사용해서 출력하세요.",
                "reference_code": "x = 15\nprint(x < 10 or x > 20)",
                "hints": [
                    "둘 중 하나만 참이어도 True가 되는 연산자를 사용하세요.",
                    "x < 10 or x > 20 을 출력해보세요.",
                    "x = 15\nprint(x < 10 or x > 20)",
                ],
            },
            {
                "id": "p3-in",
                "concept_id": "membership",
                "prompt": '과일 리스트 ["사과", "바나나", "포도"]에 "포도"가 있는지 in으로 확인해서 출력하세요.',
                "reference_code": 'fruits = ["사과", "바나나", "포도"]\nprint("포도" in fruits)',
                "hints": [
                    "값 in 리스트 형태로 포함 여부를 확인할 수 있습니다.",
                    '"포도" in fruits 를 출력해보세요.',
                    'fruits = ["사과", "바나나", "포도"]\nprint("포도" in fruits)',
                ],
            },
            {
                "id": "p4-not-in",
                "concept_id": "membership",
                "prompt": "숫자 리스트 [1, 2, 3]에 5가 없는지 not in으로 확인해서 출력하세요.",
                "reference_code": "nums = [1, 2, 3]\nprint(5 not in nums)",
                "hints": [
                    "in의 반대는 not in입니다.",
                    "5 not in nums 를 출력해보세요.",
                    "nums = [1, 2, 3]\nprint(5 not in nums)",
                ],
            },
            {
                "id": "p5-mini-ternary",
                "concept_id": "ternary",
                "prompt": '숫자 8이 짝수면 "짝수", 홀수면 "홀수"를 삼항 표현식 한 줄로 출력하세요.',
                "reference_code": 'n = 8\nprint("짝수" if n % 2 == 0 else "홀수")',
                "hints": [
                    "값1 if 조건 else 값2 형태를 print() 안에 그대로 넣을 수 있습니다.",
                    '"짝수" if n % 2 == 0 else "홀수" 를 출력해보세요.',
                    'n = 8\nprint("짝수" if n % 2 == 0 else "홀수")',
                ],
            },
        ],
    },
    {
        "id": 7,
        "title": "반복문 for",
        "goal": "정해진 횟수 또는 목록 반복하기",
        "concepts": [
            {
                "id": "for-range",
                "title": "for와 range()로 n번 반복하기",
                "explanation": "range(n)은 0부터 n-1까지의 숫자를 만들어냅니다. for 변수 in range(n): 으로 n번 반복할 수 있습니다.",
                "example_code": "for i in range(3):\n    print(i)",
            },
            {
                "id": "for-range-start-stop",
                "title": "range(시작, 끝)으로 범위 지정하기",
                "explanation": "range(시작, 끝)은 시작부터 끝-1까지 반복합니다. 끝 숫자는 포함되지 않는다는 점에 주의하세요.",
                "example_code": "for i in range(1, 4):\n    print(i)",
            },
            {
                "id": "for-loop-variable",
                "title": "반복 변수를 계산에 활용하기",
                "explanation": "반복할 때마다 바뀌는 변수(i)를 계산식에 그대로 사용할 수 있습니다.",
                "example_code": "for i in range(1, 4):\n    print(i * 2)",
            },
            {
                "id": "pass-statement",
                "title": "pass로 아무 것도 하지 않기",
                "explanation": "pass는 '여기에는 실행할 코드가 없다'는 뜻으로, 문법상 코드가 필요한 자리를 채울 때 사용합니다.",
                "example_code": 'for i in range(3):\n    if i == 1:\n        pass\n    else:\n        print(i)',
            },
        ],
        "problems": [
            {
                "id": "p1-repeat-n-times",
                "concept_id": "for-range",
                "prompt": '"Hi"를 5번, 한 줄에 하나씩 출력하세요.',
                "reference_code": 'for _ in range(5):\n    print("Hi")',
                "hints": [
                    "range(5)는 0,1,2,3,4로 다섯 번 반복하게 해줍니다.",
                    'for _ in range(5): 다음 줄에 print("Hi")를 들여써서 넣으세요.',
                    'for _ in range(5):\n    print("Hi")',
                ],
            },
            {
                "id": "p2-one-to-five",
                "concept_id": "for-range-start-stop",
                "prompt": "1부터 5까지 숫자를 한 줄씩 출력하세요.",
                "reference_code": "for i in range(1, 6):\n    print(i)",
                "hints": [
                    "1부터 5까지 포함하려면 range의 끝 숫자를 6으로 써야 합니다 (끝은 포함 안 됨).",
                    "for i in range(1, 6): 다음 줄에 print(i)를 넣으세요.",
                    "for i in range(1, 6):\n    print(i)",
                ],
            },
            {
                "id": "p3-double",
                "concept_id": "for-loop-variable",
                "prompt": "1부터 5까지 각 숫자의 두 배를 한 줄씩 출력하세요 (2, 4, 6, 8, 10).",
                "reference_code": "for i in range(1, 6):\n    print(i * 2)",
                "hints": [
                    "1부터 5까지 반복하면서, 반복 변수를 그대로 계산에 써보세요.",
                    "print(i * 2) 처럼 반복 변수 i에 2를 곱해서 출력하세요.",
                    "for i in range(1, 6):\n    print(i * 2)",
                ],
            },
            {
                "id": "p4-pass-skip",
                "concept_id": "pass-statement",
                "prompt": "1부터 5까지 반복하면서, 3일 때는 pass로 아무것도 하지 않고, 나머지 숫자만 출력하세요.",
                "reference_code": "for i in range(1, 6):\n    if i == 3:\n        pass\n    else:\n        print(i)",
                "hints": [
                    "if 조건에서 아무 동작도 하지 않으려면 pass를 씁니다.",
                    "3일 때는 pass, 그 외에는 else에서 print(i)를 실행하세요.",
                    "for i in range(1, 6):\n    if i == 3:\n        pass\n    else:\n        print(i)",
                ],
            },
            {
                "id": "p5-mini-full-table",
                "concept_id": "for-range-start-stop",
                "prompt": "2단과 3단을 순서대로 이어서 출력하세요. 각 단은 1 x 1 = 1 형식으로 9줄씩, 총 18줄입니다.",
                "reference_code": 'for n in range(2, 4):\n    for i in range(1, 10):\n        print(n, "x", i, "=", n * i)',
                "hints": [
                    "for 안에 또 다른 for를 넣어서 '단'을 바꿔가며 반복할 수 있습니다 (반복문 중첩).",
                    "바깥쪽 for n in range(2, 4)로 2단과 3단을 돌고, 안쪽 for i in range(1, 10)으로 각 단을 출력하세요.",
                    'for n in range(2, 4):\n    for i in range(1, 10):\n        print(n, "x", i, "=", n * i)',
                ],
            },
        ],
    },
    {
        "id": 8,
        "title": "반복문 while",
        "goal": "조건이 유지되는 동안 반복하기",
        "concepts": [
            {
                "id": "while-basics",
                "title": "while 기본 구조",
                "explanation": "while 조건: 은 조건이 참인 동안 계속 반복합니다. for와 달리 몇 번 반복할지 미리 정해져 있지 않을 때 씁니다.",
                "example_code": "count = 0\nwhile count < 3:\n    print(count)\n    count += 1",
            },
            {
                "id": "while-break",
                "title": "무한 루프와 break",
                "explanation": "while True: 는 조건 없이 계속 반복합니다. 원하는 순간 break를 만나면 반복문을 즉시 빠져나갑니다.",
                "example_code": 'i = 1\nwhile True:\n    print(i)\n    if i == 3:\n        break\n    i += 1',
            },
            {
                "id": "while-input",
                "title": "while과 input() 함께 쓰기",
                "explanation": "정답을 맞힐 때까지 반복해서 입력받는 것처럼, while 안에서 input()을 여러 번 호출할 수 있습니다.",
                "example_code": 'answer = 7\nguess = int(input())\nwhile guess != answer:\n    print("다시 시도하세요")\n    guess = int(input())\nprint("정답입니다!")',
                "stdin_for_example": "3\n7\n",
            },
            {
                "id": "while-else",
                "title": "while-else",
                "explanation": "while문이 break 없이 조건이 거짓이 되어 정상적으로 끝나면, else 블록이 실행됩니다. break로 중간에 빠져나오면 else는 실행되지 않습니다.",
                "example_code": 'n = 0\nwhile n < 3:\n    print(n)\n    n += 1\nelse:\n    print("종료")',
            },
        ],
        "problems": [
            {
                "id": "p1-while-count",
                "concept_id": "while-basics",
                "prompt": '0부터 4까지 "카운트: N" 형식으로 한 줄씩 출력하세요 (while 사용).',
                "reference_code": 'count = 0\nwhile count < 5:\n    print("카운트:", count)\n    count += 1',
                "hints": [
                    "count를 0에서 시작해서, count < 5인 동안 반복하면 됩니다.",
                    "반복할 때마다 출력하고 나서 count += 1로 값을 늘리는 걸 잊지 마세요.",
                    'count = 0\nwhile count < 5:\n    print("카운트:", count)\n    count += 1',
                ],
            },
            {
                "id": "p2-double-until-over-100",
                "concept_id": "while-basics",
                "prompt": "1부터 시작하는 변수에 2를 계속 곱해서, 100을 넘는 순간 멈추고 그 값을 출력하세요 (while 사용).",
                "reference_code": "n = 1\nwhile n <= 100:\n    n *= 2\nprint(n)",
                "hints": [
                    "n이 100 이하인 동안에는 계속 2를 곱하도록 while 조건을 만드세요.",
                    "반복문이 끝난 뒤에 n을 출력하면 됩니다 (반복 중에는 출력하지 않아도 돼요).",
                    "n = 1\nwhile n <= 100:\n    n *= 2\nprint(n)",
                ],
            },
            {
                "id": "p3-break-at-seven",
                "concept_id": "while-break",
                "prompt": "1부터 순서대로 늘어나는 숫자를 한 줄씩 출력하다가, 7을 출력한 뒤에 멈추세요 (1~7 출력).",
                "reference_code": "i = 1\nwhile True:\n    print(i)\n    if i == 7:\n        break\n    i += 1",
                "hints": [
                    "while True:로 무한히 반복하다가, 원하는 조건에서 break로 빠져나올 수 있습니다.",
                    "i를 출력한 다음 i가 7인지 검사해서 break하고, 아니면 i를 1 늘리세요.",
                    "i = 1\nwhile True:\n    print(i)\n    if i == 7:\n        break\n    i += 1",
                ],
            },
            {
                "id": "p4-while-else",
                "concept_id": "while-else",
                "prompt": "0부터 2까지 출력한 뒤, while문이 break 없이 끝까지 실행되면 while-else를 사용해서 \"완료\"를 출력하세요.",
                "reference_code": 'n = 0\nwhile n < 3:\n    print(n)\n    n += 1\nelse:\n    print("완료")',
                "hints": [
                    "while문 뒤에도 else를 붙일 수 있습니다. break 없이 끝나면 실행됩니다.",
                    "while n < 3: 블록이 끝난 뒤 else: 블록에서 \"완료\"를 출력하세요.",
                    'n = 0\nwhile n < 3:\n    print(n)\n    n += 1\nelse:\n    print("완료")',
                ],
            },
            {
                "id": "p5-mini-updown-game",
                "concept_id": "while-input",
                "prompt": '정답은 50입니다. input()으로 추측값을 반복 입력받아, 정답보다 작으면 "더 큰 숫자입니다", 크면 "더 작은 숫자입니다", 같으면 "정답입니다!"를 출력하고 멈추는 업다운 게임을 만드세요.',
                "reference_code": 'answer = 50\nwhile True:\n    guess = int(input())\n    if guess == answer:\n        print("정답입니다!")\n        break\n    elif guess < answer:\n        print("더 큰 숫자입니다")\n    else:\n        print("더 작은 숫자입니다")',
                "stdin": "30\n70\n50\n",
                "input_hint": "여러 줄에 걸쳐 숫자를 입력해보세요. 예: 30 / 70 / 50",
                "hints": [
                    "이전 문제에 조건을 하나 더 추가하는 것뿐입니다: 작을 때 / 클 때 / 같을 때.",
                    "elif로 '더 큰 숫자입니다'와 '더 작은 숫자입니다' 두 경우를 구분하세요.",
                    'answer = 50\nwhile True:\n    guess = int(input())\n    if guess == answer:\n        print("정답입니다!")\n        break\n    elif guess < answer:\n        print("더 큰 숫자입니다")\n    else:\n        print("더 작은 숫자입니다")',
                ],
            },
        ],
    },
    {
        "id": 9,
        "title": "리스트 심화와 컴프리헨션",
        "goal": "리스트 인덱싱·함수들과 리스트 컴프리헨션",
        "concepts": [
            {
                "id": "list-basics",
                "title": "리스트 만들고 값 꺼내기",
                "explanation": "리스트는 [ ] 안에 여러 값을 콤마로 나열해서 저장합니다. 순서(인덱스)는 0부터 시작합니다.",
                "example_code": 'fruits = ["사과", "바나나", "포도"]\nprint(fruits[1])',
            },
            {
                "id": "list-functions",
                "title": "리스트 함수들",
                "explanation": "sort()로 정렬, reverse()로 뒤집기, append()로 추가, count()로 개수 세기처럼 리스트에는 다양한 기능이 붙어 있습니다.",
                "example_code": "nums = [3, 1, 4, 1, 5]\nnums.sort()\nprint(nums)",
            },
            {
                "id": "list-comprehension",
                "title": "리스트 컴프리헨션",
                "explanation": "[식 for 변수 in 리스트] 형태로, 반복문과 조건문을 한 줄로 줄여서 새 리스트를 만들 수 있습니다.",
                "example_code": "nums = [1, 2, 3, 4, 5]\nsquares = [n ** 2 for n in nums]\nprint(squares)",
            },
        ],
        "problems": [
            {
                "id": "p1-list-index",
                "concept_id": "list-basics",
                "prompt": 'fruits 리스트에 "사과", "바나나", "포도"를 저장하고, 두 번째 항목을 출력하세요.',
                "reference_code": 'fruits = ["사과", "바나나", "포도"]\nprint(fruits[1])',
                "hints": [
                    "리스트의 순서(인덱스)는 0부터 시작합니다. 두 번째 항목의 인덱스는 몇일까요?",
                    "fruits[1]로 두 번째 항목에 접근할 수 있습니다.",
                    'fruits = ["사과", "바나나", "포도"]\nprint(fruits[1])',
                ],
            },
            {
                "id": "p2-sort",
                "concept_id": "list-functions",
                "prompt": "[3, 1, 4, 1, 5] 리스트를 sort()로 오름차순 정렬해서 출력하세요.",
                "reference_code": "nums = [3, 1, 4, 1, 5]\nnums.sort()\nprint(nums)",
                "hints": [
                    "리스트에는 .sort() 메서드가 있어서 바로 정렬할 수 있습니다.",
                    "nums.sort()를 호출한 뒤 nums를 출력하세요.",
                    "nums = [3, 1, 4, 1, 5]\nnums.sort()\nprint(nums)",
                ],
            },
            {
                "id": "p3-count",
                "concept_id": "list-functions",
                "prompt": "[1, 2, 2, 3, 2, 4] 리스트에서 2가 몇 번 나오는지 count()로 세어 출력하세요.",
                "reference_code": "nums = [1, 2, 2, 3, 2, 4]\nprint(nums.count(2))",
                "hints": [
                    "리스트.count(값)으로 특정 값이 몇 번 나오는지 셀 수 있습니다.",
                    "nums.count(2)를 출력해보세요.",
                    "nums = [1, 2, 2, 3, 2, 4]\nprint(nums.count(2))",
                ],
            },
            {
                "id": "p4-comprehension-filter",
                "concept_id": "list-comprehension",
                "prompt": "[1, 2, 3, 4, 5] 리스트에서 짝수만 골라 새 리스트로 만드는 리스트 컴프리헨션을 사용해서 출력하세요.",
                "reference_code": "nums = [1, 2, 3, 4, 5]\nevens = [n for n in nums if n % 2 == 0]\nprint(evens)",
                "hints": [
                    "[식 for 변수 in 리스트 if 조건] 형태로 조건을 추가할 수 있습니다.",
                    "[n for n in nums if n % 2 == 0]을 출력해보세요.",
                    "nums = [1, 2, 3, 4, 5]\nevens = [n for n in nums if n % 2 == 0]\nprint(evens)",
                ],
            },
            {
                "id": "p5-mini-comprehension-map",
                "concept_id": "list-comprehension",
                "prompt": "[1, 2, 3, 4, 5] 각각을 제곱한 값으로 이루어진 새 리스트를 컴프리헨션으로 만들어 출력하세요.",
                "reference_code": "nums = [1, 2, 3, 4, 5]\nsquares = [n ** 2 for n in nums]\nprint(squares)",
                "hints": [
                    "조건 없이 [식 for 변수 in 리스트] 만으로도 새 리스트를 만들 수 있습니다.",
                    "[n ** 2 for n in nums]를 출력해보세요.",
                    "nums = [1, 2, 3, 4, 5]\nsquares = [n ** 2 for n in nums]\nprint(squares)",
                ],
            },
        ],
    },
    {
        "id": 10,
        "title": "튜플과 집합",
        "goal": "값을 바꿀 수 없는 튜플과 중복 없는 집합",
        "concepts": [
            {
                "id": "tuple-basics",
                "title": "튜플",
                "explanation": "튜플은 리스트와 비슷하지만 ( )로 감싸고, 한 번 만들면 값을 바꿀 수 없습니다(불변).",
                "example_code": "point = (3, 4)\nprint(point[0])",
            },
            {
                "id": "set-basics",
                "title": "집합 (set)",
                "explanation": "집합은 중복을 허용하지 않고 순서가 없는 자료형입니다. 리스트를 set()으로 감싸면 중복이 자동으로 제거됩니다.",
                "example_code": "numbers = set([1, 2, 2, 3])\nprint(numbers)",
            },
            {
                "id": "set-operations",
                "title": "집합 연산",
                "explanation": "&(교집합), |(합집합), -(차집합)로 두 집합 사이의 관계를 계산할 수 있습니다.",
                "example_code": "a = {1, 2, 3}\nb = {2, 3, 4}\nprint(a & b)",
            },
        ],
        "problems": [
            {
                "id": "p1-tuple-index",
                "concept_id": "tuple-basics",
                "prompt": "튜플 (3, 4)를 만들고 첫 번째 값을 출력하세요.",
                "reference_code": "point = (3, 4)\nprint(point[0])",
                "hints": [
                    "튜플도 리스트처럼 인덱스로 값을 꺼낼 수 있습니다.",
                    "point[0]을 출력해보세요.",
                    "point = (3, 4)\nprint(point[0])",
                ],
            },
            {
                "id": "p2-set-dedupe",
                "concept_id": "set-basics",
                "prompt": "리스트 [1, 1, 2, 2, 3, 3]을 집합으로 만들어서 중복이 제거된 결과를 출력하세요.",
                "reference_code": "nums = [1, 1, 2, 2, 3, 3]\nprint(set(nums))",
                "hints": [
                    "set(리스트)로 리스트를 집합으로 바꿀 수 있습니다.",
                    "set(nums)를 출력해보세요.",
                    "nums = [1, 1, 2, 2, 3, 3]\nprint(set(nums))",
                ],
            },
            {
                "id": "p3-intersection",
                "concept_id": "set-operations",
                "prompt": "집합 {1, 2, 3, 4}와 {3, 4, 5, 6}의 교집합을 출력하세요.",
                "reference_code": "a = {1, 2, 3, 4}\nb = {3, 4, 5, 6}\nprint(a & b)",
                "hints": [
                    "두 집합 모두에 있는 값만 남기는 연산자를 떠올려 보세요.",
                    "a & b를 출력해보세요.",
                    "a = {1, 2, 3, 4}\nb = {3, 4, 5, 6}\nprint(a & b)",
                ],
            },
            {
                "id": "p4-union",
                "concept_id": "set-operations",
                "prompt": "집합 {1, 2, 3}와 {3, 4, 5}의 합집합을 출력하세요.",
                "reference_code": "a = {1, 2, 3}\nb = {3, 4, 5}\nprint(a | b)",
                "hints": [
                    "두 집합의 모든 값을 합치는 연산자를 떠올려 보세요.",
                    "a | b를 출력해보세요.",
                    "a = {1, 2, 3}\nb = {3, 4, 5}\nprint(a | b)",
                ],
            },
            {
                "id": "p5-mini-difference",
                "concept_id": "set-operations",
                "prompt": "집합 {1, 2, 3, 4, 5}에서 {2, 4}를 뺀 차집합을 출력하세요.",
                "reference_code": "a = {1, 2, 3, 4, 5}\nb = {2, 4}\nprint(a - b)",
                "hints": [
                    "한 집합에서 다른 집합의 값을 제외하는 연산자를 떠올려 보세요.",
                    "a - b를 출력해보세요.",
                    "a = {1, 2, 3, 4, 5}\nb = {2, 4}\nprint(a - b)",
                ],
            },
        ],
    },
    {
        "id": 11,
        "title": "딕셔너리 심화",
        "goal": "get(), keys/values/items()로 딕셔너리 다루기",
        "concepts": [
            {
                "id": "dict-basics",
                "title": "딕셔너리 기본",
                "explanation": "딕셔너리는 {키: 값} 형태로 저장합니다. 순서가 아니라 키(key)로 값을 찾습니다.",
                "example_code": 'person = {"name": "파이코치", "age": 5}\nprint(person["name"])',
            },
            {
                "id": "dict-get",
                "title": "get()으로 안전하게 조회하기",
                "explanation": "딕셔너리[키]로 없는 키를 조회하면 오류가 나지만, get(키, 기본값)을 쓰면 키가 없을 때 오류 대신 기본값을 돌려줍니다.",
                "example_code": 'd = {"a": 1}\nprint(d.get("b", "없음"))',
            },
            {
                "id": "dict-iteration",
                "title": "keys()/values()/items()로 전체 순회하기",
                "explanation": "keys()는 모든 키를, values()는 모든 값을, items()는 (키, 값) 쌍을 모두 꺼낼 때 사용합니다.",
                "example_code": 'd = {"a": 1, "b": 2}\nfor k, v in d.items():\n    print(k, v)',
            },
        ],
        "problems": [
            {
                "id": "p1-dict-lookup",
                "concept_id": "dict-basics",
                "prompt": 'person 딕셔너리에 "name": "파이코치", "age": 5 를 저장하고, "파이코치는 5살입니다" 형식으로 출력하세요.',
                "reference_code": 'person = {"name": "파이코치", "age": 5}\nprint(person["name"] + "는 " + str(person["age"]) + "살입니다")',
                "hints": [
                    '딕셔너리 값은 person["키"] 형태로 꺼낼 수 있습니다.',
                    "age는 숫자라서 문자열과 이어붙이려면 str()로 문자열로 바꿔야 합니다.",
                    'person = {"name": "파이코치", "age": 5}\nprint(person["name"] + "는 " + str(person["age"]) + "살입니다")',
                ],
            },
            {
                "id": "p2-dict-get",
                "concept_id": "dict-get",
                "prompt": '딕셔너리 {"사과": 1000, "바나나": 1500}에서 get()으로 "포도" 가격을 조회하되, 없으면 "없음"을 출력하세요.',
                "reference_code": 'prices = {"사과": 1000, "바나나": 1500}\nprint(prices.get("포도", "없음"))',
                "hints": [
                    "get(키, 기본값)을 쓰면 키가 없을 때 오류 대신 기본값을 돌려받습니다.",
                    'prices.get("포도", "없음")을 출력해보세요.',
                    'prices = {"사과": 1000, "바나나": 1500}\nprint(prices.get("포도", "없음"))',
                ],
            },
            {
                "id": "p3-dict-keys",
                "concept_id": "dict-iteration",
                "prompt": '딕셔너리 {"a": 1, "b": 2, "c": 3}의 모든 key를 한 줄씩 출력하세요.',
                "reference_code": 'd = {"a": 1, "b": 2, "c": 3}\nfor k in d.keys():\n    print(k)',
                "hints": [
                    "keys()는 딕셔너리의 모든 키를 순서대로 돌려줍니다.",
                    "for k in d.keys(): 다음 줄에 print(k)를 넣으세요.",
                    'd = {"a": 1, "b": 2, "c": 3}\nfor k in d.keys():\n    print(k)',
                ],
            },
            {
                "id": "p4-dict-values-sum",
                "concept_id": "dict-iteration",
                "prompt": '딕셔너리 {"a": 1, "b": 2, "c": 3}의 모든 value의 합을 출력하세요.',
                "reference_code": 'd = {"a": 1, "b": 2, "c": 3}\nprint(sum(d.values()))',
                "hints": [
                    "values()는 딕셔너리의 모든 값만 모아서 돌려줍니다.",
                    "sum(d.values())를 출력해보세요.",
                    'd = {"a": 1, "b": 2, "c": 3}\nprint(sum(d.values()))',
                ],
            },
            {
                "id": "p5-mini-items",
                "concept_id": "dict-iteration",
                "prompt": '딕셔너리 {"사과": 1000, "바나나": 1500, "포도": 3000}의 모든 key와 value를 "상품: 가격" 형식으로 한 줄씩 출력하세요 (items() 사용).',
                "reference_code": 'prices = {"사과": 1000, "바나나": 1500, "포도": 3000}\nfor k, v in prices.items():\n    print(k + ": " + str(v))',
                "hints": [
                    "items()는 (키, 값) 쌍을 함께 돌려줘서 for k, v in d.items(): 형태로 동시에 꺼낼 수 있습니다.",
                    "v는 숫자이니 문자열과 합치려면 str()로 바꿔야 합니다.",
                    'prices = {"사과": 1000, "바나나": 1500, "포도": 3000}\nfor k, v in prices.items():\n    print(k + ": " + str(v))',
                ],
            },
        ],
    },
    {
        "id": 12,
        "title": "함수와 스코프",
        "goal": "def/매개변수/return과 지역·전역 변수",
        "concepts": [
            {
                "id": "def-basics",
                "title": "함수 정의와 호출",
                "explanation": "def 이름(): 으로 함수를 만들고, 이름() 으로 호출해서 실행합니다. 같은 코드를 여러 번 쓰지 않아도 됩니다.",
                "example_code": 'def greet():\n    print("안녕하세요!")\n\ngreet()',
            },
            {
                "id": "def-params",
                "title": "매개변수로 값 전달하기",
                "explanation": "함수 이름 옆 괄호에 매개변수를 적으면, 호출할 때마다 다른 값을 넘겨서 다르게 동작시킬 수 있습니다.",
                "example_code": 'def welcome(name):\n    print(name + "님 환영합니다!")\n\nwelcome("파이코치")',
            },
            {
                "id": "def-return",
                "title": "return으로 값 돌려받기",
                "explanation": "return은 함수의 결과값을 호출한 곳으로 돌려줍니다. print와 달리 그 값을 변수에 저장해서 다시 쓸 수 있습니다.",
                "example_code": "def add(a, b):\n    return a + b\n\nprint(add(3, 4))",
            },
            {
                "id": "scope",
                "title": "지역변수와 전역변수",
                "explanation": "함수 안에서 만든 변수(지역변수)는 함수 밖에서 쓸 수 없습니다. 함수 밖에서 만든 변수(전역변수)는 함수 안에서 읽을 수 있습니다.",
                "example_code": 'x = 10\ndef show():\n    print(x)\n\nshow()',
            },
        ],
        "problems": [
            {
                "id": "p1-simple-function",
                "concept_id": "def-basics",
                "prompt": '인사말을 출력하는 greet 함수를 만들고 호출해서 "안녕하세요!"를 출력하세요.',
                "reference_code": 'def greet():\n    print("안녕하세요!")\n\ngreet()',
                "hints": [
                    "def 함수이름(): 다음 줄에 들여쓰기로 실행할 코드를 씁니다.",
                    "함수를 만든 뒤에는 함수이름() 으로 직접 호출해야 실행됩니다.",
                    'def greet():\n    print("안녕하세요!")\n\ngreet()',
                ],
            },
            {
                "id": "p2-function-param",
                "concept_id": "def-params",
                "prompt": '이름을 매개변수로 받아 "OOO님 환영합니다!"를 출력하는 welcome(name) 함수를 만들고, welcome("파이코치")로 호출하세요.',
                "reference_code": 'def welcome(name):\n    print(name + "님 환영합니다!")\n\nwelcome("파이코치")',
                "hints": [
                    "함수 괄호 안에 매개변수 이름을 적으면 함수 안에서 그 값을 변수처럼 쓸 수 있습니다.",
                    'welcome("파이코치")처럼 호출할 때 괄호 안에 실제 값을 넣습니다.',
                    'def welcome(name):\n    print(name + "님 환영합니다!")\n\nwelcome("파이코치")',
                ],
            },
            {
                "id": "p3-return-value",
                "concept_id": "def-return",
                "prompt": "두 수를 더해서 돌려주는 add(a, b) 함수를 만들고, add(3, 4)의 결과를 출력하세요.",
                "reference_code": "def add(a, b):\n    return a + b\n\nprint(add(3, 4))",
                "hints": [
                    "함수 안에서 print 대신 return을 쓰면 값을 함수 밖으로 돌려줄 수 있습니다.",
                    "add(3, 4)의 결과를 print()로 감싸서 출력하세요.",
                    "def add(a, b):\n    return a + b\n\nprint(add(3, 4))",
                ],
            },
            {
                "id": "p4-scope",
                "concept_id": "scope",
                "prompt": '전역변수 message = "안녕"을 만들고, 이를 출력하는 함수 show_message()를 만들어 호출하세요.',
                "reference_code": 'message = "안녕"\ndef show_message():\n    print(message)\n\nshow_message()',
                "hints": [
                    "함수 밖에서 만든 변수는 함수 안에서도 읽을 수 있습니다.",
                    "함수 안에서 message를 새로 만들지 말고, 그냥 print(message)만 하면 됩니다.",
                    'message = "안녕"\ndef show_message():\n    print(message)\n\nshow_message()',
                ],
            },
            {
                "id": "p5-mini-calculator-functions",
                "concept_id": "def-return",
                "prompt": 'add(a, b), subtract(a, b), multiply(a, b) 세 함수를 만들고, input()으로 숫자 두 개를 받아 각 함수의 결과를 "합: N", "차: N", "곱: N" 형식으로 출력하세요.',
                "reference_code": 'def add(a, b):\n    return a + b\n\ndef subtract(a, b):\n    return a - b\n\ndef multiply(a, b):\n    return a * b\n\nx = int(input())\ny = int(input())\nprint("합:", add(x, y))\nprint("차:", subtract(x, y))\nprint("곱:", multiply(x, y))',
                "stdin": "6\n2\n",
                "input_hint": "숫자를 한 줄씩 입력해보세요. 예: 6 / 2",
                "hints": [
                    "세 함수 모두 두 개의 매개변수를 받아 계산 결과를 return하는 형태로 만드세요.",
                    "함수를 다 만든 뒤, input()으로 받은 두 값을 각 함수에 넘겨서 결과를 출력하세요.",
                    'def add(a, b):\n    return a + b\n\ndef subtract(a, b):\n    return a - b\n\ndef multiply(a, b):\n    return a * b\n\nx = int(input())\ny = int(input())\nprint("합:", add(x, y))\nprint("차:", subtract(x, y))\nprint("곱:", multiply(x, y))',
                ],
            },
        ],
    },
    {
        "id": 13,
        "title": "함수 심화",
        "goal": "기본값 파라미터, 가변 인자(*args), 람다",
        "concepts": [
            {
                "id": "default-param",
                "title": "기본값 파라미터",
                "explanation": "def func(a, b=10): 처럼 매개변수에 기본값을 정해두면, 호출할 때 값을 생략할 수 있습니다.",
                "example_code": 'def greet(name="손님"):\n    print(name + "님 안녕하세요")\n\ngreet()',
            },
            {
                "id": "args",
                "title": "가변 파라미터 (*args)",
                "explanation": "*args를 쓰면 개수 제한 없이 여러 인자를 받을 수 있습니다. 함수 안에서는 튜플로 묶여서 다뤄집니다.",
                "example_code": "def total(*args):\n    return sum(args)\n\nprint(total(1, 2, 3))",
            },
            {
                "id": "lambda",
                "title": "람다(lambda) 함수",
                "explanation": "람다는 이름 없이 한 줄로 만드는 간단한 함수입니다. '매개변수: 결과식' 형태로 씁니다.",
                "example_code": "square = lambda x: x ** 2\nprint(square(5))",
            },
        ],
        "problems": [
            {
                "id": "p1-default-param",
                "concept_id": "default-param",
                "prompt": '이름을 매개변수로 받되 기본값이 "손님"인 greet(name="손님") 함수를 만드세요. 인자 없이 호출한 결과와 "파이코치"를 넣어 호출한 결과를 순서대로 출력하세요.',
                "reference_code": 'def greet(name="손님"):\n    print(name + "님 안녕하세요")\n\ngreet()\ngreet("파이코치")',
                "hints": [
                    "매개변수에 = 기본값을 붙이면 호출할 때 생략할 수 있습니다.",
                    "greet()는 기본값 손님을, greet(\"파이코치\")는 파이코치를 사용합니다.",
                    'def greet(name="손님"):\n    print(name + "님 안녕하세요")\n\ngreet()\ngreet("파이코치")',
                ],
            },
            {
                "id": "p2-args-sum",
                "concept_id": "args",
                "prompt": "*args를 사용해서 개수 제한 없이 숫자를 받아 모두 더한 값을 돌려주는 total(*args) 함수를 만들고, total(1, 2, 3, 4)를 출력하세요.",
                "reference_code": "def total(*args):\n    return sum(args)\n\nprint(total(1, 2, 3, 4))",
                "hints": [
                    "매개변수 앞에 *를 붙이면 여러 개의 인자를 튜플 하나로 받을 수 있습니다.",
                    "sum(args)로 튜플 안의 모든 값을 더할 수 있습니다.",
                    "def total(*args):\n    return sum(args)\n\nprint(total(1, 2, 3, 4))",
                ],
            },
            {
                "id": "p3-lambda-square",
                "concept_id": "lambda",
                "prompt": "숫자를 받아 제곱을 돌려주는 람다 함수 square를 만들고 square(6)을 출력하세요.",
                "reference_code": "square = lambda x: x ** 2\nprint(square(6))",
                "hints": [
                    "lambda 매개변수: 결과식 형태로 한 줄 함수를 만들 수 있습니다.",
                    "square = lambda x: x ** 2 처럼 변수에 저장해서 함수처럼 호출하세요.",
                    "square = lambda x: x ** 2\nprint(square(6))",
                ],
            },
            {
                "id": "p4-lambda-bigger",
                "concept_id": "lambda",
                "prompt": "두 숫자를 받아 더 큰 값을 돌려주는 람다 함수 bigger를 만들고 bigger(3, 8)을 출력하세요.",
                "reference_code": "bigger = lambda a, b: a if a > b else b\nprint(bigger(3, 8))",
                "hints": [
                    "람다 안에서도 삼항 표현식(값1 if 조건 else 값2)을 쓸 수 있습니다.",
                    "lambda a, b: a if a > b else b 를 만들어보세요.",
                    "bigger = lambda a, b: a if a > b else b\nprint(bigger(3, 8))",
                ],
            },
            {
                "id": "p5-mini-discount-total",
                "concept_id": "default-param",
                "prompt": "할인율(기본값 0)과 *args로 여러 가격을 받아, 할인 적용 총합을 돌려주는 total_price(discount=0, *prices) 함수를 만드세요. total_price(0, 1000, 2000, 3000)과 total_price(0.1, 1000, 2000, 3000)을 순서대로 출력하세요.",
                "reference_code": "def total_price(discount=0, *prices):\n    return sum(prices) * (1 - discount)\n\nprint(total_price(0, 1000, 2000, 3000))\nprint(total_price(0.1, 1000, 2000, 3000))",
                "hints": [
                    "기본값 파라미터와 *args를 함께 쓸 수 있습니다. 기본값 파라미터를 먼저 적으세요.",
                    "sum(prices)로 전체 합을 구한 뒤 (1 - discount)를 곱하면 할인이 적용됩니다.",
                    "def total_price(discount=0, *prices):\n    return sum(prices) * (1 - discount)\n\nprint(total_price(0, 1000, 2000, 3000))\nprint(total_price(0.1, 1000, 2000, 3000))",
                ],
            },
        ],
    },
    {
        "id": 14,
        "title": "예외처리",
        "goal": "try/except/finally로 오류에 대응하기",
        "concepts": [
            {
                "id": "try-except-basics",
                "title": "try/except 기본 구조",
                "explanation": "try 블록에서 오류가 발생하면 프로그램이 멈추는 대신, except 블록의 코드가 실행됩니다.",
                "example_code": 'try:\n    print(10 / 0)\nexcept ZeroDivisionError:\n    print("0으로 나눌 수 없어요")',
            },
            {
                "id": "specific-exceptions",
                "title": "구체적인 예외 처리하기",
                "explanation": "ValueError, IndexError처럼 오류 종류에 맞는 except를 쓰면, 어떤 문제가 생겼는지 정확히 대응할 수 있습니다.",
                "example_code": 'try:\n    print(int("abc"))\nexcept ValueError:\n    print("숫자로 변환할 수 없어요")',
            },
            {
                "id": "finally",
                "title": "finally",
                "explanation": "finally 블록은 예외가 발생하든 안 하든 항상 마지막에 실행됩니다. 마무리 작업을 넣을 때 사용합니다.",
                "example_code": 'try:\n    print(1)\nfinally:\n    print("항상 실행")',
            },
        ],
        "problems": [
            {
                "id": "p1-zero-division",
                "concept_id": "try-except-basics",
                "prompt": '10을 0으로 나누는 코드를 try/except로 감싸서, ZeroDivisionError가 나면 "0으로 나눌 수 없어요"를 출력하세요.',
                "reference_code": 'try:\n    print(10 / 0)\nexcept ZeroDivisionError:\n    print("0으로 나눌 수 없어요")',
                "hints": [
                    "0으로 나누면 어떤 종류의 오류(Error)가 나는지 떠올려 보세요.",
                    "try 블록 안에 문제가 되는 코드를, except ZeroDivisionError: 안에 대체 코드를 넣으세요.",
                    'try:\n    print(10 / 0)\nexcept ZeroDivisionError:\n    print("0으로 나눌 수 없어요")',
                ],
            },
            {
                "id": "p2-value-error",
                "concept_id": "specific-exceptions",
                "prompt": '"abc"를 int()로 변환하는 코드를 try/except로 감싸서, ValueError가 나면 "숫자로 변환할 수 없어요"를 출력하세요.',
                "reference_code": 'try:\n    print(int("abc"))\nexcept ValueError:\n    print("숫자로 변환할 수 없어요")',
                "hints": [
                    "숫자로 바꿀 수 없는 문자열을 int()에 넣으면 어떤 오류가 날지 떠올려 보세요.",
                    "except ValueError: 블록에 대체 메시지를 출력하세요.",
                    'try:\n    print(int("abc"))\nexcept ValueError:\n    print("숫자로 변환할 수 없어요")',
                ],
            },
            {
                "id": "p3-index-error",
                "concept_id": "specific-exceptions",
                "prompt": "리스트 [1, 2, 3]에서 인덱스 10을 조회하는 코드를 try/except로 감싸서, IndexError가 나면 \"범위를 벗어났어요\"를 출력하세요.",
                "reference_code": 'nums = [1, 2, 3]\ntry:\n    print(nums[10])\nexcept IndexError:\n    print("범위를 벗어났어요")',
                "hints": [
                    "리스트 범위를 벗어난 인덱스로 접근하면 IndexError가 발생합니다.",
                    "try 블록에 nums[10]을, except IndexError: 블록에 대체 메시지를 넣으세요.",
                    'nums = [1, 2, 3]\ntry:\n    print(nums[10])\nexcept IndexError:\n    print("범위를 벗어났어요")',
                ],
            },
            {
                "id": "p4-finally",
                "concept_id": "finally",
                "prompt": 'try 블록에서 정상적으로 5를 출력한 뒤, finally 블록에서 "완료"를 항상 출력하세요.',
                "reference_code": 'try:\n    print(5)\nfinally:\n    print("완료")',
                "hints": [
                    "예외가 없어도 finally 블록은 항상 실행됩니다.",
                    "try: 안에 print(5), finally: 안에 완료 메시지를 넣으세요.",
                    'try:\n    print(5)\nfinally:\n    print("완료")',
                ],
            },
            {
                "id": "p5-mini-safe-convert",
                "concept_id": "specific-exceptions",
                "prompt": '문자열 리스트 ["10", "abc", "20"] 각각을 int()로 변환해서 출력하되, 변환할 수 없는 값은 "abc는 숫자가 아닙니다" 형식으로 출력하세요 (for문 + try/except).',
                "reference_code": 'values = ["10", "abc", "20"]\nfor v in values:\n    try:\n        print(int(v))\n    except ValueError:\n        print(v + "는 숫자가 아닙니다")',
                "hints": [
                    "for로 리스트를 순회하면서, 각 값마다 try/except를 적용하세요.",
                    "변환에 실패하면 except 블록에서 v를 그대로 활용해 메시지를 만드세요.",
                    'values = ["10", "abc", "20"]\nfor v in values:\n    try:\n        print(int(v))\n    except ValueError:\n        print(v + "는 숫자가 아닙니다")',
                ],
            },
        ],
    },
    {
        "id": 15,
        "title": "클래스 기초",
        "goal": "class, self, __init__로 나만의 객체 만들기",
        "concepts": [
            {
                "id": "class-instance",
                "title": "클래스와 인스턴스",
                "explanation": "class는 객체를 만들기 위한 설계도입니다. 설계도로 실제 만들어낸 객체를 인스턴스라고 합니다.",
                "example_code": "class Dog:\n    pass\n\nmy_dog = Dog()\nprint(type(my_dog))",
            },
            {
                "id": "init-self",
                "title": "__init__과 self",
                "explanation": "__init__은 인스턴스가 만들어질 때 자동으로 실행되는 초기화 함수입니다. self는 그 인스턴스 자기 자신을 가리킵니다.",
                "example_code": 'class Person:\n    def __init__(self, name):\n        self.name = name\n\np = Person("파이코치")\nprint(p.name)',
            },
            {
                "id": "methods",
                "title": "메서드",
                "explanation": "클래스 안에 정의된 함수를 메서드라고 합니다. 첫 번째 매개변수는 항상 self이고, 인스턴스.메서드() 형태로 호출합니다.",
                "example_code": 'class Person:\n    def __init__(self, name):\n        self.name = name\n\n    def greet(self):\n        print(self.name + "입니다")\n\np = Person("파이코치")\np.greet()',
            },
        ],
        "problems": [
            {
                "id": "p1-dog-class",
                "concept_id": "init-self",
                "prompt": '이름을 속성으로 갖는 Dog 클래스를 만드세요. __init__(self, name)에서 self.name에 저장하고, Dog("초코")로 인스턴스를 만들어 name을 출력하세요.',
                "reference_code": 'class Dog:\n    def __init__(self, name):\n        self.name = name\n\nmy_dog = Dog("초코")\nprint(my_dog.name)',
                "hints": [
                    "__init__(self, name) 안에서 self.name = name으로 저장하세요.",
                    'Dog("초코")로 인스턴스를 만든 뒤 my_dog.name을 출력하세요.',
                    'class Dog:\n    def __init__(self, name):\n        self.name = name\n\nmy_dog = Dog("초코")\nprint(my_dog.name)',
                ],
            },
            {
                "id": "p2-person-introduce",
                "concept_id": "methods",
                "prompt": '이름과 나이를 속성으로 갖는 Person 클래스를 만드세요. introduce(self) 메서드가 "파이코치는 5살입니다" 형식으로 출력하도록 만들고, Person("파이코치", 5)를 만들어 introduce()를 호출하세요.',
                "reference_code": 'class Person:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n\n    def introduce(self):\n        print(self.name + "는 " + str(self.age) + "살입니다")\n\np = Person("파이코치", 5)\np.introduce()',
                "hints": [
                    "__init__에서 name과 age를 각각 self.name, self.age에 저장하세요.",
                    "introduce(self) 메서드 안에서는 self.name, self.age로 속성에 접근합니다.",
                    'class Person:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n\n    def introduce(self):\n        print(self.name + "는 " + str(self.age) + "살입니다")\n\np = Person("파이코치", 5)\np.introduce()',
                ],
            },
            {
                "id": "p3-counter-class",
                "concept_id": "methods",
                "prompt": "count를 0으로 초기화하는 Counter 클래스를 만드세요. increase(self) 메서드를 호출할 때마다 count가 1씩 늘어나게 만들고, increase()를 세 번 호출한 뒤 count를 출력하세요.",
                "reference_code": "class Counter:\n    def __init__(self):\n        self.count = 0\n\n    def increase(self):\n        self.count += 1\n\nc = Counter()\nc.increase()\nc.increase()\nc.increase()\nprint(c.count)",
                "hints": [
                    "__init__(self)에서 self.count = 0으로 시작하세요.",
                    "increase(self) 안에서 self.count += 1을 실행하세요.",
                    "class Counter:\n    def __init__(self):\n        self.count = 0\n\n    def increase(self):\n        self.count += 1\n\nc = Counter()\nc.increase()\nc.increase()\nc.increase()\nprint(c.count)",
                ],
            },
            {
                "id": "p4-circle-area",
                "concept_id": "methods",
                "prompt": "반지름을 속성으로 갖는 Circle 클래스를 만드세요. area(self) 메서드가 반지름 * 반지름 * 3.14를 돌려주도록 만들고, Circle(5)의 넓이를 출력하세요.",
                "reference_code": "class Circle:\n    def __init__(self, radius):\n        self.radius = radius\n\n    def area(self):\n        return self.radius * self.radius * 3.14\n\nc = Circle(5)\nprint(c.area())",
                "hints": [
                    "__init__에서 radius를 self.radius에 저장하세요.",
                    "area(self)는 print가 아니라 return으로 값을 돌려줘야, 밖에서 print(c.area())로 출력할 수 있습니다.",
                    "class Circle:\n    def __init__(self, radius):\n        self.radius = radius\n\n    def area(self):\n        return self.radius * self.radius * 3.14\n\nc = Circle(5)\nprint(c.area())",
                ],
            },
            {
                "id": "p5-mini-account",
                "concept_id": "methods",
                "prompt": "잔액을 속성으로 갖는 Account 클래스를 만드세요. deposit(self, amount)로 입금하면 잔액이 늘고, withdraw(self, amount)로 출금하면 잔액이 줄어듭니다. 잔액 1000으로 시작해서 500 입금, 300 출금한 뒤 최종 잔액을 출력하세요.",
                "reference_code": "class Account:\n    def __init__(self, balance):\n        self.balance = balance\n\n    def deposit(self, amount):\n        self.balance += amount\n\n    def withdraw(self, amount):\n        self.balance -= amount\n\naccount = Account(1000)\naccount.deposit(500)\naccount.withdraw(300)\nprint(account.balance)",
                "hints": [
                    "__init__(self, balance)에서 self.balance = balance로 시작 잔액을 저장하세요.",
                    "deposit은 self.balance += amount, withdraw는 self.balance -= amount 입니다.",
                    "class Account:\n    def __init__(self, balance):\n        self.balance = balance\n\n    def deposit(self, amount):\n        self.balance += amount\n\n    def withdraw(self, amount):\n        self.balance -= amount\n\naccount = Account(1000)\naccount.deposit(500)\naccount.withdraw(300)\nprint(account.balance)",
                ],
            },
        ],
    },
    {
        "id": 16,
        "title": "모듈과 파일",
        "goal": "파일 저장·불러오기와 코드 가져오기",
        "concepts": [
            {
                "id": "file-write",
                "title": "파일에 쓰기",
                "explanation": 'open("파일명", "w")로 파일을 쓰기 모드로 열고 write()로 내용을 저장합니다. with 문을 쓰면 자동으로 파일이 닫힙니다.',
                "example_code": 'with open("memo.txt", "w") as f:\n    f.write("안녕하세요")',
            },
            {
                "id": "file-read",
                "title": "파일 읽기",
                "explanation": 'open("파일명")으로 파일을 열고 read()로 전체 내용을 문자열로 가져올 수 있습니다.',
                "example_code": 'with open("memo.txt", "w") as f:\n    f.write("안녕하세요")\n\nwith open("memo.txt") as f:\n    print(f.read())',
            },
            {
                "id": "import-module",
                "title": "import로 모듈 가져오기",
                "explanation": "import 모듈이름 으로 다른 파일(모듈)에 이미 만들어진 기능을 가져와 쓸 수 있습니다. math는 수학 계산을 위한 표준 모듈입니다.",
                "example_code": "import math\nprint(math.sqrt(16))",
            },
        ],
        "problems": [
            {
                "id": "p1-write-read",
                "concept_id": "file-write",
                "prompt": 'memo.txt 파일에 "오늘의 다짐: 꾸준히 하자"를 저장한 뒤, 파일을 다시 읽어서 내용을 출력하세요.',
                "reference_code": 'with open("memo.txt", "w") as f:\n    f.write("오늘의 다짐: 꾸준히 하자")\n\nwith open("memo.txt") as f:\n    print(f.read())',
                "hints": [
                    'with open("memo.txt", "w") as f: 다음 줄에서 f.write(...)로 저장합니다.',
                    '저장한 뒤에는 open("memo.txt")로 다시 열어서 f.read()로 내용을 가져와 출력하세요.',
                    'with open("memo.txt", "w") as f:\n    f.write("오늘의 다짐: 꾸준히 하자")\n\nwith open("memo.txt") as f:\n    print(f.read())',
                ],
            },
            {
                "id": "p2-write-multiline",
                "concept_id": "file-read",
                "prompt": 'todo.txt 파일에 "숙제"와 "운동"을 줄바꿈으로 구분해서 저장한 뒤, 파일을 읽어서 그대로 출력하세요.',
                "reference_code": 'with open("todo.txt", "w") as f:\n    f.write("숙제\\n운동")\n\nwith open("todo.txt") as f:\n    print(f.read())',
                "hints": [
                    "문자열 안에 \\n을 넣으면 파일 안에서도 줄이 바뀝니다.",
                    'f.write("숙제\\n운동") 처럼 한 번에 두 줄을 저장할 수 있습니다.',
                    'with open("todo.txt", "w") as f:\n    f.write("숙제\\n운동")\n\nwith open("todo.txt") as f:\n    print(f.read())',
                ],
            },
            {
                "id": "p3-math-sqrt",
                "concept_id": "import-module",
                "prompt": "math 모듈을 가져와서 16의 제곱근을 출력하세요.",
                "reference_code": "import math\nprint(math.sqrt(16))",
                "hints": [
                    "가장 먼저 import math로 모듈을 가져와야 합니다.",
                    "제곱근 함수는 math.sqrt(숫자) 형태로 사용합니다.",
                    "import math\nprint(math.sqrt(16))",
                ],
            },
            {
                "id": "p4-math-floor",
                "concept_id": "import-module",
                "prompt": "math 모듈의 floor 함수를 사용해서 7.8을 내림한 값을 출력하세요.",
                "reference_code": "import math\nprint(math.floor(7.8))",
                "hints": [
                    "내림(소수점 버리기) 함수는 math 모듈 안에 있습니다.",
                    "math.floor(숫자) 형태로 사용해보세요.",
                    "import math\nprint(math.floor(7.8))",
                ],
            },
            {
                "id": "p5-mini-memo-saver",
                "concept_id": "file-write",
                "prompt": 'input()으로 메모 내용을 입력받아 notes.txt에 저장하고, 저장 직후 파일을 다시 읽어 "저장된 메모: OOO" 형식으로 출력하세요.',
                "reference_code": 'memo = input()\nwith open("notes.txt", "w") as f:\n    f.write(memo)\n\nwith open("notes.txt") as f:\n    saved = f.read()\nprint("저장된 메모: " + saved)',
                "stdin": "오늘도 화이팅\n",
                "input_hint": "메모로 남길 문장을 입력해보세요. 예: 오늘도 화이팅",
                "hints": [
                    "input()으로 받은 값을 변수에 저장한 뒤, 그 변수를 파일에 write하세요.",
                    "저장 후 파일을 다시 열어 read()로 읽은 값을 saved 같은 변수에 담아 출력하세요.",
                    'memo = input()\nwith open("notes.txt", "w") as f:\n    f.write(memo)\n\nwith open("notes.txt") as f:\n    saved = f.read()\nprint("저장된 메모: " + saved)',
                ],
            },
        ],
    },
]
